apiVersion: v1
kind: Service
metadata:
  name: zalenium
  labels:
    app: zalenium
spec:
  type: NodePort
  ports:
  - port: 4444
    name: zaleniumgridport
    protocol: TCP
    targetPort: 4444
    nodePort: 30000
  selector:
    app: zalenium
    role: grid